using GPTipsBot.Config;
using GPTipsBot.Models;
using GPTipsBot.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;

namespace GPTipsBot.Db
{
    public sealed class ApplicationContext : DbContext
    {
        public Guid Guid { get; }
        public DbSet<User> Users { get; set; } = null!;
        public DbSet<Message> Messages { get; set; } = null!;
        public DbSet<BotSettings> BotSettings { get; set; } = null!;
        public DbSet<OpenaiAccount> OpenaiAccounts { get; set; } = null!;
        public DbSet<UserCommand> UserCommands { get; set; } = null!;
        public DbSet<Transaction> Transactions { get; set; } = null!;
        public DbSet<Invoice> Invoices { get; set; } = null!;
        public DbSet<Wallet> Wallets { get; set; } = null!;
        public DbSet<PaymentHold> PaymentHolds { get; set; } = null!;
        public DbSet<ConversationMeta> ConversationMetas { get; set; } = null!;
        public DbSet<AuthLoginEvent> AuthLoginEvents { get; set; } = null!;

        public ApplicationContext()
        {
            EnsureAppSchema();
            EnsureYooKassaInvoiceColumns();
            EnsureFreePhotoAnimationsColumn();
            EnsureFreeSummaryRequestsColumn();
            EnsurePaymentHoldsTable();
            EnsureMessageThreadIdColumn();
            EnsurePreferredGptModelColumn();
            EnsureConversationMetasTable();
            EnsureAuthLoginEventsTable();
            EnsureEmailAuthColumns();
            EnsureTelegramIdColumn();
            Guid = Guid.NewGuid();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ConversationMeta>(e =>
            {
                e.HasKey(x => new { x.UserId, x.ContextId });
            });
        }
        
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(AppConfig.ConnectionString);
        }

        /// <summary>
        /// EnsureCreated skips when any tables exist (e.g. Quartz). Create EF tables if missing.
        /// </summary>
        private void EnsureAppSchema()
        {
            Database.EnsureCreated();

            try
            {
                _ = Users.AsNoTracking().Any();
            }
            catch
            {
                var creator = Database.GetService<IRelationalDatabaseCreator>();
                creator.CreateTables();
            }
        }

        /// <summary>
        /// EnsureCreated does not alter existing tables; add YooKassa columns idempotently.
        /// </summary>
        private void EnsureYooKassaInvoiceColumns()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "Provider" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "ExternalPaymentId" text NULL;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "FiatAmountKopecks" bigint NULL;
                """);
        }

        /// <summary>
        /// EnsureCreated does not alter existing tables; add free animation counter idempotently.
        /// </summary>
        private void EnsureFreePhotoAnimationsColumn()
        {
            Database.ExecuteSqlRaw($"""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FreePhotoAnimations" integer NOT NULL DEFAULT {PaymentConfig.NewbieFreePhotoAnimations};
                """);
        }

        private void EnsureFreeSummaryRequestsColumn()
        {
            Database.ExecuteSqlRaw($"""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FreeSummaryRequests" integer NOT NULL DEFAULT {PaymentConfig.NewbieFreeSummaries};
                """);
        }

        private void EnsurePaymentHoldsTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "PaymentHolds" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" bigint NOT NULL,
                    "Feature" integer NOT NULL,
                    "UsedFreeQuota" boolean NOT NULL,
                    "WalletAmount" double precision NOT NULL,
                    "Status" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_PaymentHolds_Status_CreatedAt" ON "PaymentHolds" ("Status", "CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_PaymentHolds_UserId" ON "PaymentHolds" ("UserId");
                """);
        }

        private void EnsureMessageThreadIdColumn()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "MessageThreadId" bigint NULL;
                CREATE INDEX IF NOT EXISTS "IX_Messages_ChatId_MessageThreadId_CreatedAt"
                    ON "Messages" ("ChatId", "MessageThreadId", "CreatedAt");
                """);
        }

        private void EnsurePreferredGptModelColumn()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "BotSettings" ADD COLUMN IF NOT EXISTS "PreferredGptModel" text NULL;
                """);
        }

        private void EnsureConversationMetasTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "ConversationMetas" (
                    "UserId" bigint NOT NULL,
                    "ContextId" bigint NOT NULL,
                    "CustomTitle" text NULL,
                    "IsPinned" boolean NOT NULL DEFAULT false,
                    "IsDeleted" boolean NOT NULL DEFAULT false,
                    PRIMARY KEY ("UserId", "ContextId")
                );
                CREATE INDEX IF NOT EXISTS "IX_ConversationMetas_UserId_IsDeleted"
                    ON "ConversationMetas" ("UserId", "IsDeleted");
                """);
        }

        private void EnsureAuthLoginEventsTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "AuthLoginEvents" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" bigint NOT NULL,
                    "Provider" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_AuthLoginEvents_Provider_CreatedAt"
                    ON "AuthLoginEvents" ("Provider", "CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_AuthLoginEvents_UserId_CreatedAt"
                    ON "AuthLoginEvents" ("UserId", "CreatedAt");
                """);
        }

        private void EnsureEmailAuthColumns()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "Email" text NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PasswordHash" text NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailConfirmed" boolean NOT NULL DEFAULT false;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailConfirmCode" text NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailConfirmExpiresAt" timestamp with time zone NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email_Unique"
                    ON "Users" ("Email")
                    WHERE "Email" IS NOT NULL;
                """);
        }

        private void EnsureTelegramIdColumn()
        {
            // One-time schema + safe backfill. After account merge the deactivated Telegram row
            // keeps Id=telegramId with TelegramId=NULL; never re-assign that Id if another row
            // already owns the TelegramId (linked email survivor).
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TelegramId" bigint NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_TelegramId_Unique"
                    ON "Users" ("TelegramId")
                    WHERE "TelegramId" IS NOT NULL;
                """);

            Database.ExecuteSqlRaw($"""
                UPDATE "Users" AS u
                SET "TelegramId" = u."Id"
                WHERE u."TelegramId" IS NULL
                  AND u."IsActive" = true
                  AND u."Id" > 0
                  AND u."Id" < {WebAuthConstants.EmailIdBase}
                  AND (u."Email" IS NULL OR u."Source" IS DISTINCT FROM 'web-email')
                  AND NOT EXISTS (
                      SELECT 1 FROM "Users" AS x
                      WHERE x."TelegramId" = u."Id"
                  );
                """);
        }
    }
}
