using GPTipsBot.Config;
using GPTipsBot.Models;
using GPTipsBot.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;

namespace GPTipsBot.Db
{
    public sealed class ApplicationContext : DbContext
    {
        public Guid Guid { get; }
        public DbSet<User> Users { get; set; } = null!;
        public DbSet<Message> Messages { get; set; } = null!;
        public DbSet<BotSettings> BotSettings { get; set; } = null!;
        public DbSet<OpenaiAccount> OpenaiAccounts { get; set; } = null!;
        public DbSet<UserCommand> UserCommands { get; set; } = null!;
        public DbSet<Transaction> Transactions { get; set; } = null!;
        public DbSet<Invoice> Invoices { get; set; } = null!;
        public DbSet<Wallet> Wallets { get; set; } = null!;
        public DbSet<PaymentHold> PaymentHolds { get; set; } = null!;
        public DbSet<ConversationMeta> ConversationMetas { get; set; } = null!;
        public DbSet<AuthLoginEvent> AuthLoginEvents { get; set; } = null!;
        public DbSet<GuestFingerprintQuota> GuestFingerprintQuotas { get; set; } = null!;
        public DbSet<BroadcastCampaign> BroadcastCampaigns { get; set; } = null!;

        public ApplicationContext()
        {
            EnsureAppSchema();
            EnsureYooKassaInvoiceColumns();
            EnsureFreePhotoAnimationsColumn();
            EnsureFreeAlicePhotoQuotasColumns();
            EnsureFreeSummaryRequestsColumn();
            EnsurePaymentHoldsTable();
            EnsureGemWallets();
            EnsureMessageThreadIdColumn();
            EnsurePreferredGptModelColumn();
            EnsureConversationMetasTable();
            EnsureAuthLoginEventsTable();
            EnsureEmailAuthColumns();
            EnsureTelegramIdColumn();
            EnsureYandexIdColumn();
            EnsureGuestFingerprintQuotasTable();
            EnsureBroadcastCampaignsTable();
            Guid = Guid.NewGuid();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ConversationMeta>(e =>
            {
                e.HasKey(x => new { x.UserId, x.ContextId });
            });
            modelBuilder.Entity<GuestFingerprintQuota>(e =>
            {
                e.HasKey(x => x.Fingerprint);
            });
        }
        
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(AppConfig.ConnectionString);
        }

        /// <summary>
        /// EnsureCreated skips when any tables exist (e.g. Quartz). Create EF tables if missing.
        /// </summary>
        private void EnsureAppSchema()
        {
            Database.EnsureCreated();

            try
            {
                _ = Users.AsNoTracking().Any();
            }
            catch
            {
                var creator = Database.GetService<IRelationalDatabaseCreator>();
                creator.CreateTables();
            }
        }

        /// <summary>
        /// EnsureCreated does not alter existing tables; add YooKassa columns idempotently.
        /// </summary>
        private void EnsureYooKassaInvoiceColumns()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "Provider" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "ExternalPaymentId" text NULL;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "FiatAmountKopecks" bigint NULL;
                """);
        }

        /// <summary>
        /// EnsureCreated does not alter existing tables; add free animation counter idempotently.
        /// </summary>
        private void EnsureFreePhotoAnimationsColumn()
        {
            Database.ExecuteSqlRaw($"""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FreePhotoAnimations" integer NOT NULL DEFAULT {PaymentConfig.NewbieFreePhotoAnimations};
                """);
        }

        private void EnsureFreeAlicePhotoQuotasColumns()
        {
            Database.ExecuteSqlRaw($"""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FreeCombinePhotos" integer NOT NULL DEFAULT {PaymentConfig.NewbieFreeCombinePhotos};
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FreeChangePhotos" integer NOT NULL DEFAULT {PaymentConfig.NewbieFreeChangePhotos};
                """);
        }

        private void EnsureFreeSummaryRequestsColumn()
        {
            Database.ExecuteSqlRaw($"""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FreeSummaryRequests" integer NOT NULL DEFAULT {PaymentConfig.NewbieFreeSummaries};
                """);
        }

        private void EnsurePaymentHoldsTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "PaymentHolds" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" bigint NOT NULL,
                    "Feature" integer NOT NULL,
                    "UsedFreeQuota" boolean NOT NULL,
                    "WalletAmount" bigint NOT NULL,
                    "Status" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_PaymentHolds_Status_CreatedAt" ON "PaymentHolds" ("Status", "CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_PaymentHolds_UserId" ON "PaymentHolds" ("UserId");
                """);
        }

        /// <summary>
        /// Converts the wallet from the old star unit (a double priced at 10 ₽) to gems (a whole
        /// number priced at a kopeck), multiplying every stored balance and hold by a thousand so
        /// purchasing power is unchanged. Keyed off the column type, so it runs exactly once per
        /// database and is a no-op on a freshly created one.
        /// </summary>
        /// <remarks>
        /// A finite balance can never overflow bigint at this multiplier — only NaN/±Infinity (both
        /// legal to store in a double precision column, both meaningless as a wallet balance) or a
        /// pre-existing astronomically large value can. Those are clamped to 0 rather than left to
        /// crash the whole app on every future startup; investigate how they got there separately
        /// (see GPTipsBotTests or an ad-hoc SELECT for the affected UserId) before assuming 0 is final.
        /// </remarks>
        private void EnsureGemWallets()
        {
            Database.ExecuteSqlRaw("""
                DO $$
                BEGIN
                    LOCK TABLE "Wallets" IN ACCESS EXCLUSIVE MODE;
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Wallets' AND column_name = 'Balance'
                          AND data_type = 'double precision'
                    ) THEN
                        ALTER TABLE "Wallets"
                            ALTER COLUMN "Balance" TYPE bigint
                            USING CASE
                                WHEN "Balance" IS NULL
                                  OR "Balance" != "Balance"
                                  OR "Balance" = 'Infinity'::float8
                                  OR "Balance" = '-Infinity'::float8
                                  OR abs("Balance") > 1e15
                                THEN 0::bigint
                                ELSE ROUND(("Balance" * 200)::numeric)::bigint
                            END;
                        UPDATE "Wallets" SET "Currency" = 'GEM';
                    END IF;

                    LOCK TABLE "PaymentHolds" IN ACCESS EXCLUSIVE MODE;
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'PaymentHolds' AND column_name = 'WalletAmount'
                          AND data_type = 'double precision'
                    ) THEN
                        ALTER TABLE "PaymentHolds"
                            ALTER COLUMN "WalletAmount" TYPE bigint
                            USING CASE
                                WHEN "WalletAmount" IS NULL
                                  OR "WalletAmount" != "WalletAmount"
                                  OR "WalletAmount" = 'Infinity'::float8
                                  OR "WalletAmount" = '-Infinity'::float8
                                  OR abs("WalletAmount") > 1e15
                                THEN 0::bigint
                                ELSE ROUND(("WalletAmount" * 200)::numeric)::bigint
                            END;
                    END IF;
                END $$;
                """);
        }

        private void EnsureMessageThreadIdColumn()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "MessageThreadId" bigint NULL;
                CREATE INDEX IF NOT EXISTS "IX_Messages_ChatId_MessageThreadId_CreatedAt"
                    ON "Messages" ("ChatId", "MessageThreadId", "CreatedAt");
                """);
        }

        private void EnsurePreferredGptModelColumn()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "BotSettings" ADD COLUMN IF NOT EXISTS "PreferredGptModel" text NULL;
                """);
        }

        private void EnsureConversationMetasTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "ConversationMetas" (
                    "UserId" bigint NOT NULL,
                    "ContextId" bigint NOT NULL,
                    "CustomTitle" text NULL,
                    "IsPinned" boolean NOT NULL DEFAULT false,
                    "IsDeleted" boolean NOT NULL DEFAULT false,
                    PRIMARY KEY ("UserId", "ContextId")
                );
                CREATE INDEX IF NOT EXISTS "IX_ConversationMetas_UserId_IsDeleted"
                    ON "ConversationMetas" ("UserId", "IsDeleted");
                """);
        }

        private void EnsureAuthLoginEventsTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "AuthLoginEvents" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" bigint NOT NULL,
                    "Provider" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_AuthLoginEvents_Provider_CreatedAt"
                    ON "AuthLoginEvents" ("Provider", "CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_AuthLoginEvents_UserId_CreatedAt"
                    ON "AuthLoginEvents" ("UserId", "CreatedAt");
                """);
        }

        private void EnsureEmailAuthColumns()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "Email" text NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PasswordHash" text NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailConfirmed" boolean NOT NULL DEFAULT false;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailConfirmCode" text NULL;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailConfirmExpiresAt" timestamp with time zone NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email_Unique"
                    ON "Users" ("Email")
                    WHERE "Email" IS NOT NULL;
                """);
        }

        private void EnsureTelegramIdColumn()
        {
            // One-time schema + safe backfill. After account merge the deactivated Telegram row
            // keeps Id=telegramId with TelegramId=NULL; never re-assign that Id if another row
            // already owns the TelegramId (linked email survivor).
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TelegramId" bigint NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_TelegramId_Unique"
                    ON "Users" ("TelegramId")
                    WHERE "TelegramId" IS NOT NULL;
                """);

            Database.ExecuteSqlRaw($"""
                UPDATE "Users" AS u
                SET "TelegramId" = u."Id"
                WHERE u."TelegramId" IS NULL
                  AND u."IsActive" = true
                  AND u."Id" > 0
                  AND u."Id" < {WebAuthConstants.EmailIdBase}
                  AND (u."Email" IS NULL OR u."Source" IS DISTINCT FROM 'web-email')
                  AND NOT EXISTS (
                      SELECT 1 FROM "Users" AS x
                      WHERE x."TelegramId" = u."Id"
                  );
                """);
        }

        private void EnsureYandexIdColumn()
        {
            Database.ExecuteSqlRaw("""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "YandexId" text NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_YandexId_Unique"
                    ON "Users" ("YandexId")
                    WHERE "YandexId" IS NOT NULL;
                """);
        }

        private void EnsureGuestFingerprintQuotasTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "GuestFingerprintQuotas" (
                    "Fingerprint" text NOT NULL PRIMARY KEY,
                    "GuestUserId" bigint NOT NULL,
                    "IpHash" text NULL,
                    "CreatedAt" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_GuestFingerprintQuotas_IpHash_CreatedAt"
                    ON "GuestFingerprintQuotas" ("IpHash", "CreatedAt");
                """);
        }

        private void EnsureBroadcastCampaignsTable()
        {
            Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "BroadcastCampaigns" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "CreatedByTelegramId" bigint NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "StartedAt" timestamp with time zone NULL,
                    "FinishedAt" timestamp with time zone NULL,
                    "Status" integer NOT NULL,
                    "ConfigJson" text NOT NULL,
                    "LastUserId" bigint NOT NULL DEFAULT 0,
                    "SentCount" integer NOT NULL DEFAULT 0,
                    "FailedCount" integer NOT NULL DEFAULT 0,
                    "SkippedCount" integer NOT NULL DEFAULT 0,
                    "BlockedCount" integer NOT NULL DEFAULT 0,
                    "TotalTargeted" integer NOT NULL DEFAULT 0,
                    "LastError" text NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_BroadcastCampaigns_Status"
                    ON "BroadcastCampaigns" ("Status");
                """);
        }
    }
}
