//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTipsBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPTipsBot.Resources.BotResponse", typeof(BotResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс.
        /// </summary>
        public static string AddMoneyResponse {
            get {
                return ResourceManager.GetString("AddMoneyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1️⃣ Фото.
        /// </summary>
        public static string AnimateExampleBeforeCaption {
            get {
                return ResourceManager.GetString("AnimateExampleBeforeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2️⃣ Промпт: «Дети радостно прыгают и обнимаются».
        /// </summary>
        public static string AnimateExamplePromptCaption {
            get {
                return ResourceManager.GetString("AnimateExamplePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3️⃣ Результат.
        /// </summary>
        public static string AnimateExampleResultCaption {
            get {
                return ResourceManager.GetString("AnimateExampleResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VPN для всей семьи всего за 150руб в месяц](https://t.me/t_consult_service_bot?start=referral_486363646)
        ///
        ///🎁 Первые 2 дня бесплатно
        ///🚀 Высокая скорость
        ///▶️ Доступ к ютуб, инстаграмм, СhatGpt из России без рекламы
        ///📱💻 Для телефонов, компьютеров и планшетов
        ///👩‍👩‍👧‍👧 Можно подключить несколько устройств на одну подписку.
        /// </summary>
        public static string AdvertisementText {
            get {
                return ResourceManager.GetString("AdvertisementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤖 ChatGPT + изображения....
        /// </summary>
        public static string BotDescription {
            get {
                return ResourceManager.GetString("BotDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🤖 Подробная инструкция....
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatGPT + DALL-E | Бесплатный | Sora.
        /// </summary>
        public static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция отменена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось распознать текст.
        /// </summary>
        public static string CantRecognizeText {
            get {
                return ResourceManager.GetString("CantRecognizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста выберите язык интерфейса.
        /// </summary>
        public static string ChooseLanguagePlease {
            get {
                return ResourceManager.GetString("ChooseLanguagePlease", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Что сделать с изображением?.
        /// </summary>
        public static string ChooseImagesPlease {
            get {
                return ResourceManager.GetString("ChooseImagesPlease", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Контекст успешно сброшен. Начните новый диалог.
        /// </summary>
        public static string ContextUpdated {
            get {
                return ResourceManager.GetString("ContextUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте сообщение, чтобы продолжить диалог.
        /// </summary>
        public static string ContinueConversation {
            get {
                return ResourceManager.GetString("ContinueConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куки для Bing image обновлены.
        /// </summary>
        public static string CookiesUpdated {
            get {
                return ResourceManager.GetString("CookiesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Дневной лимит в {0} запросов исчерпан. Ждем вас завтра.
        /// </summary>
        public static string DailyLimitViolation {
            get {
                return ResourceManager.GetString("DailyLimitViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1⭐ = 10 запросов к ChatGpt или 2 генерации изображения
        ///
        ///Минимальное пополнение: {0} ₽ ({1}⭐)
        ///Выберите пакет или введите целое число stars:.
        /// </summary>
        public static string DepositResponse {
            get {
                return ResourceManager.GetString("DepositResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPTipDev.
        /// </summary>
        public static string DevBotName {
            get {
                return ResourceManager.GetString("DevBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👇 Введите целое число старсов для отправки доната. Мы рады любой вашей поддержке 🤗.
        /// </summary>
        public static string DonateInstructions {
            get {
                return ResourceManager.GetString("DonateInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌟 Поддержите наш проект! 💪
        ///
        ///💖 Каждый донат помогает развивать и улучшать сервис. 🤝 Мы ценим вашу поддержку и работаем над тем, чтобы сделать наш продукт еще лучше. 🚀💡.
        /// </summary>
        public static string DonateResponse {
            get {
                return ResourceManager.GetString("DonateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за вашу поддержку!.
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Донат проекту {0} stars.
        /// </summary>
        public static string DonateTitle {
            get {
                return ResourceManager.GetString("DonateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет!:) Чем могу помочь?.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовое описание изображения должно быть не более {0} символов. Сократите описание и отправьте заново.
        /// </summary>
        public static string ImageDescriptionLimitWarning {
            get {
                return ResourceManager.GetString("ImageDescriptionLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы продолжить введите текстовое описание длиной до {0} символов
        ///
        ///1:1 - квадратное изображение
        ///2:1 - прямоугольное (по умолчанию).
        /// </summary>
        public static string InputImageDescriptionText {
            get {
                return ResourceManager.GetString("InputImageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо иметь {0} stars для выполнения операции
        ///
        ///После пополнения выберите команду заново.
        /// </summary>
        public static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Нужно минимум {0} ₽ ({1}⭐). Выберите пакет или введите сумму снова 👇.
        /// </summary>
        public static string InvalidDepositAmountResponse {
            get {
                return ResourceManager.GetString("InvalidDepositAmountResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 stars  = 20 запросов к ChatGpt или 2 генерации изображения.
        /// </summary>
        public static string InvoiceText {
            get {
                return ResourceManager.GetString("InvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс.
        /// </summary>
        public static string InvoiceTitle {
            get {
                return ResourceManager.GetString("InvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руссий язык используется для интерфейса.
        /// </summary>
        public static string LanguageWasSetSuccessfully {
            get {
                return ResourceManager.GetString("LanguageWasSetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Ведутся технические работы. Благодарим за понимание..
        /// </summary>
        public static string OnMaintenance {
            get {
                return ResourceManager.GetString("OnMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык интерфейса(влияет только на перевод кнопок, общаться можно на люом языке).
        /// </summary>
        public static string PleaseSetLanguage {
            get {
                return ResourceManager.GetString("PleaseSetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌛️ Подождите, подготавливаю ответ....
        /// </summary>
        public static string PleaseWaitMsg {
            get {
                return ResourceManager.GetString("PleaseWaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌛️ Генерация видео занимает в срднем от 5 до 10 минут. Подождите, подготавливаю ответ....
        /// </summary>
        public static string PleaseWaitVideoMsg {
            get {
                return ResourceManager.GetString("PleaseWaitVideoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Профиль: {0} {1}
        ///
        ///
        ///💵 Баланс: {2} Stars 💵
        ///Количество бесплатных запросов:
        /// -- запросов к ChatGpt: {3}
        /// -- генераций изображений: {4}
        /// -- распознаваний текста: {5}
        ///.
        /// </summary>
        public static string ProfileResponse {
            get {
                return ResourceManager.GetString("ProfileResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я отутствовал какое-то время, но сейчас снова в строю..
        /// </summary>
        public static string Recovered {
            get {
                return ResourceManager.GetString("Recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите промпт для анимации, используйте глаголы.
        /// </summary>
        public static string SendAnimatePrompt {
            get {
                return ResourceManager.GetString("SendAnimatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сообщение ниже. Будем рады любой обратной связи..
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для распознавания текста на изображении сначала выберите команду из меню.
        /// </summary>
        public static string SendImageTextRecognitionCommandFirst {
            get {
                return ResourceManager.GetString("SendImageTextRecognitionCommandFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы составить промпт по изображению, сначала выберите команду из меню.
        /// </summary>
        public static string SendPromptFromImageCommandFirst {
            get {
                return ResourceManager.GetString("SendPromptFromImageCommandFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте изображение — я составлю по нему промпт для генерации похожей картинки.
        /// </summary>
        public static string SendPromptFromImagePhoto {
            get {
                return ResourceManager.GetString("SendPromptFromImagePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🪄 Промпт по изображению:.
        /// </summary>
        public static string PromptFromImageHeader {
            get {
                return ResourceManager.GetString("PromptFromImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an expert prompt engineer....
        /// </summary>
        public static string PromptFromImageSystemPrompt {
            get {
                return ResourceManager.GetString("PromptFromImageSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a detailed text-to-image prompt for this image..
        /// </summary>
        public static string PromptFromImageUserPrompt {
            get {
                return ResourceManager.GetString("PromptFromImageUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте своё фото для оживления и кратко опишите действие. Например: «смеются», «танцует», «пишет».
        /// </summary>
        public static string SendPhotoToAnimate {
            get {
                return ResourceManager.GetString("SendPhotoToAnimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте изображение для распознавания текста.
        /// </summary>
        public static string SendTextRecognitionImage {
            get {
                return ResourceManager.GetString("SendTextRecognitionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бот отвечает на вопросы и создает изображения🤖👋 (@my_super_ultra_smart_bot).
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служебный бот для разработки, добавляйте @GPTipsBot.
        /// </summary>
        public static string ShortDevDescription {
            get {
                return ResourceManager.GetString("ShortDevDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Закончился лимит бесплатных запросов на сегодня.
        ///Пополните баланс или дождитесь обновления бесплатных лимитов
        ///
        ///1⭐ = 10 запросам к ChatGpt или 2 генерации изображения.
        /// </summary>
        public static string SimpleNoFreeRequests {
            get {
                return ResourceManager.GetString("SimpleNoFreeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так, попробуйте ещё раз.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Почти получилось! Просто введите число (например, 5, 10 или 50) – каждая звёздочка важна! 🌟 Спасибо вам!.
        /// </summary>
        public static string StarsDonationHint {
            get {
                return ResourceManager.GetString("StarsDonationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Закончился лимит бесплатных запросов на сегодня.
        ///Пополните баланс или дождитесь обновления бесплатных запросов через {0:%d} д {0:%h} ч {0:%m} мин
        ///
        ///1⭐ = 10 запросов к ChatGPT или 2 генерации изображения.
        /// </summary>
        public static string TimeNoFreeRequests {
            get {
                return ResourceManager.GetString("TimeNoFreeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество токенов в вашем сообщении {1} превышает лимит в {0} токенов. Сократите своё сообщение. Считайте, что в одном слове содержится примерно 1 токен.
        /// </summary>
        public static string TokensLimitExceeded {
            get {
                return ResourceManager.GetString("TokensLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Слишком много запросов в минуту, попробуйте позже.
        /// </summary>
        public static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, бот не поддерживает данный тип сообщений.
        /// </summary>
        public static string UnsupportedMessageType {
            get {
                return ResourceManager.GetString("UnsupportedMessageType", resourceCulture);
            }
        }
        
        public static string PhotoAnimationDownloading {
            get {
                return ResourceManager.GetString("PhotoAnimationDownloading", resourceCulture);
            }
        }
        
        public static string PhotoAnimationUploading {
            get {
                return ResourceManager.GetString("PhotoAnimationUploading", resourceCulture);
            }
        }
        
        public static string PhotoAnimationGenerating {
            get {
                return ResourceManager.GetString("PhotoAnimationGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏳ Генерация видео... осталось примерно {0}.
        /// </summary>
        public static string PhotoAnimationWaiting {
            get {
                return ResourceManager.GetString("PhotoAnimationWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось оживить фото. Попробуйте позже или выберите другое изображение..
        /// </summary>
        public static string PhotoAnimationFailed {
            get {
                return ResourceManager.GetString("PhotoAnimationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение на {0}⭐ ({1} ₽)
        ///
        ///Выберите способ оплаты:.
        /// </summary>
        public static string ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭐ Telegram Stars.
        /// </summary>
        public static string PayWithStarsButton {
            get {
                return ResourceManager.GetString("PayWithStarsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}⭐ · {1} ₽.
        /// </summary>
        public static string DepositPackageButton {
            get {
                return ResourceManager.GetString("DepositPackageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💳 Карта / СБП / SberPay · {0} ₽.
        /// </summary>
        public static string PayWithYooKassaButton {
            get {
                return ResourceManager.GetString("PayWithYooKassaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата {0}⭐ ({1} ₽)
        ///
        ///Нажмите кнопку ниже, чтобы открыть платёжную форму ЮKassa.
        ///После успешной оплаты баланс пополнится автоматически..
        /// </summary>
        public static string YooKassaPaymentLinkResponse {
            get {
                return ResourceManager.GetString("YooKassaPaymentLinkResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к оплате.
        /// </summary>
        public static string OpenYooKassaPaymentButton {
            get {
                return ResourceManager.GetString("OpenYooKassaPaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить оплату.
        /// </summary>
        public static string CheckYooKassaPaymentButton {
            get {
                return ResourceManager.GetString("CheckYooKassaPaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата ещё не поступила. Если вы уже заплатили — подождите минуту и нажмите снова..
        /// </summary>
        public static string YooKassaPaymentCheckPending {
            get {
                return ResourceManager.GetString("YooKassaPaymentCheckPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата найдена, баланс обновлён ✅.
        /// </summary>
        public static string YooKassaPaymentCheckOk {
            get {
                return ResourceManager.GetString("YooKassaPaymentCheckOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса GPTipsBot: {0} stars.
        /// </summary>
        public static string YooKassaPaymentDescription {
            get {
                return ResourceManager.GetString("YooKassaPaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Оплата прошла успешно! Баланс пополнен..
        /// </summary>
        public static string YooKassaPaymentSucceeded {
            get {
                return ResourceManager.GetString("YooKassaPaymentSucceeded", resourceCulture);
            }
        }
        
        public static string ReplySentPrivately {
            get {
                return ResourceManager.GetString("ReplySentPrivately", resourceCulture);
            }
        }
        
        public static string OpenPrivateChatFirst {
            get {
                return ResourceManager.GetString("OpenPrivateChatFirst", resourceCulture);
            }
        }
        
        public static string SummaryEmpty {
            get {
                return ResourceManager.GetString("SummaryEmpty", resourceCulture);
            }
        }
        
        public static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        public static string SummaryPrompt {
            get {
                return ResourceManager.GetString("SummaryPrompt", resourceCulture);
            }
        }
        
        public static string GroupCommandNotAvailable {
            get {
                return ResourceManager.GetString("GroupCommandNotAvailable", resourceCulture);
            }
        }
        
        public static string AskUsage {
            get {
                return ResourceManager.GetString("AskUsage", resourceCulture);
            }
        }

        public static string InlineAskTitle {
            get {
                return ResourceManager.GetString("InlineAskTitle", resourceCulture);
            }
        }

        public static string InlineAskDescription {
            get {
                return ResourceManager.GetString("InlineAskDescription", resourceCulture);
            }
        }

        public static string InlineAskPending {
            get {
                return ResourceManager.GetString("InlineAskPending", resourceCulture);
            }
        }

        public static string InlineImageTitle {
            get {
                return ResourceManager.GetString("InlineImageTitle", resourceCulture);
            }
        }

        public static string InlineImageTitleShort {
            get {
                return ResourceManager.GetString("InlineImageTitleShort", resourceCulture);
            }
        }

        public static string InlineImageDescription {
            get {
                return ResourceManager.GetString("InlineImageDescription", resourceCulture);
            }
        }

        public static string InlineImagePending {
            get {
                return ResourceManager.GetString("InlineImagePending", resourceCulture);
            }
        }

        public static string InlineHelpAskTitle {
            get {
                return ResourceManager.GetString("InlineHelpAskTitle", resourceCulture);
            }
        }

        public static string InlineHelpAskDescription {
            get {
                return ResourceManager.GetString("InlineHelpAskDescription", resourceCulture);
            }
        }

        public static string InlineHelpAskMessage {
            get {
                return ResourceManager.GetString("InlineHelpAskMessage", resourceCulture);
            }
        }

        public static string InlineHelpImageTitle {
            get {
                return ResourceManager.GetString("InlineHelpImageTitle", resourceCulture);
            }
        }

        public static string InlineHelpImageDescription {
            get {
                return ResourceManager.GetString("InlineHelpImageDescription", resourceCulture);
            }
        }

        public static string InlineHelpImageMessage {
            get {
                return ResourceManager.GetString("InlineHelpImageMessage", resourceCulture);
            }
        }

        public static string InlineResultExpired {
            get {
                return ResourceManager.GetString("InlineResultExpired", resourceCulture);
            }
        }

        public static string InlineRunButton {
            get {
                return ResourceManager.GetString("InlineRunButton", resourceCulture);
            }
        }

        public static string AccountLinkSuccess {
            get {
                return ResourceManager.GetString("AccountLinkSuccess", resourceCulture);
            }
        }

        public static string AccountLinkTokenInvalid {
            get {
                return ResourceManager.GetString("AccountLinkTokenInvalid", resourceCulture);
            }
        }

        public static string AccountLinkAlreadyLinked {
            get {
                return ResourceManager.GetString("AccountLinkAlreadyLinked", resourceCulture);
            }
        }

        public static string AccountLinkFailed {
            get {
                return ResourceManager.GetString("AccountLinkFailed", resourceCulture);
            }
        }

        public static string ChooseModel {
            get {
                return ResourceManager.GetString("ChooseModel", resourceCulture);
            }
        }

        public static string ModelSelected {
            get {
                return ResourceManager.GetString("ModelSelected", resourceCulture);
            }
        }

        public static string ModelSelectionRequiresBalance {
            get {
                return ResourceManager.GetString("ModelSelectionRequiresBalance", resourceCulture);
            }
        }

        public static string ModelNeedsBalance {
            get {
                return ResourceManager.GetString("ModelNeedsBalance", resourceCulture);
            }
        }

        public static string UnknownModel {
            get {
                return ResourceManager.GetString("UnknownModel", resourceCulture);
            }
        }

        public static string GptImageGenerateIntro {
            get {
                return ResourceManager.GetString("GptImageGenerateIntro", resourceCulture);
            }
        }

        public static string GptImageEditIntro {
            get {
                return ResourceManager.GetString("GptImageEditIntro", resourceCulture);
            }
        }

        public static string GptImageSendPhotoFirst {
            get {
                return ResourceManager.GetString("GptImageSendPhotoFirst", resourceCulture);
            }
        }

        public static string GptImageSendPrompt {
            get {
                return ResourceManager.GetString("GptImageSendPrompt", resourceCulture);
            }
        }

        public static string GptImageSendEditPrompt {
            get {
                return ResourceManager.GetString("GptImageSendEditPrompt", resourceCulture);
            }
        }

        public static string GptImageDoneCaption {
            get {
                return ResourceManager.GetString("GptImageDoneCaption", resourceCulture);
            }
        }
    }
}
