//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTipsBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPTipsBot.Resources.BotResponse", typeof(BotResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс.
        /// </summary>
        public static string AddMoneyResponse {
            get {
                return ResourceManager.GetString("AddMoneyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VPN в телеграмме всего за 150руб в месяц](https://t.me/t_consult_service_bot?start=referral_486363646)
        ///
        ///🎁 Первые 2 дня бесплатно
        ///🚀 Высокая скорость
        ///▶️ Доступ к ютуб, инстаграмм, СhatGpt из России
        ///📱💻 Для телефонов, компьютеров и планшетов.
        /// </summary>
        public static string AdvertisementText {
            get {
                return ResourceManager.GetString("AdvertisementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤖 Добро пожаловать в бот ChatGPT! 🚀
        ///
        ///Задавайте вопросы ChatGPT - искусственному интеллекту на основе архитектуры GPT-3.5, разработанному OpenAI. 💬
        ///
        ///- чтобы задать вопрос боту, просто отправьте текст
        ///- для генерации изображения введите команду /image, либо воспользуйтесь кнопкой меню
        ///
        ///Внимание, число бесплатных запросов ограничено. Команда для просмотра лимитов: /profile.
        /// </summary>
        public static string BotDescription {
            get {
                return ResourceManager.GetString("BotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatGPT + DALL-E | Бесплатный | Sora.
        /// </summary>
        public static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция отменена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось распознать текст.
        /// </summary>
        public static string CantRecognizeText {
            get {
                return ResourceManager.GetString("CantRecognizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста выберите язык интерфейса.
        /// </summary>
        public static string ChooseLanguagePlease {
            get {
                return ResourceManager.GetString("ChooseLanguagePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контекст успешно сброшен. Начните новый диалог.
        /// </summary>
        public static string ContextUpdated {
            get {
                return ResourceManager.GetString("ContextUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куки для Bing image обновлены.
        /// </summary>
        public static string CookiesUpdated {
            get {
                return ResourceManager.GetString("CookiesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Дневной лимит в {0} запросов исчерпан. Ждем вас завтра.
        /// </summary>
        public static string DailyLimitViolation {
            get {
                return ResourceManager.GetString("DailyLimitViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1⭐ = 20 запросов к ChatGpt или 2 генерации изображения
        ///
        ///Минимальное количество старс для пополнения: {0}
        ///Введите целое количество stars для пополнения баланса:.
        /// </summary>
        public static string DepositResponse {
            get {
                return ResourceManager.GetString("DepositResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPTipDev.
        /// </summary>
        public static string DevBotName {
            get {
                return ResourceManager.GetString("DevBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет!:) Чем могу помочь?.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовое описание изображения должно быть не более {0} символов. Сократите описание и начните заново с команды /image.
        /// </summary>
        public static string ImageDescriptionLimitWarning {
            get {
                return ResourceManager.GetString("ImageDescriptionLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Превышен дневной лимит запросов на генерацию изображений (&gt; {0}).
        /// </summary>
        public static string ImagesPerDayLimit {
            get {
                return ResourceManager.GetString("ImagesPerDayLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы продолжить введите текстовое описание длиной до {0} символов. Для выхода из режима генерации изображений введите /cancel или нажмите кнопку &apos;Отмена&apos;.
        /// </summary>
        public static string InputImageDescriptionText {
            get {
                return ResourceManager.GetString("InputImageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо иметь {0} stars для выполнения операции
        ///
        ///После пополнения введите команду /music заново.
        /// </summary>
        public static string InsufficientBalanceForMusic {
            get {
                return ResourceManager.GetString("InsufficientBalanceForMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо иметь {0} stars для выполнения операции
        ///
        ///После пополнения введите команду /video заново.
        /// </summary>
        public static string InsufficientBalanceForVideo {
            get {
                return ResourceManager.GetString("InsufficientBalanceForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Неправильный ввод количества старсов
        ///Минимальное количество для пополнения: {0} старс
        ///Введите число еще раз:.
        /// </summary>
        public static string InvalidDepositAmountResponse {
            get {
                return ResourceManager.GetString("InvalidDepositAmountResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 stars  = 20 запросов к ChatGpt или 2 генерации изображения.
        /// </summary>
        public static string InvoiceText {
            get {
                return ResourceManager.GetString("InvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс.
        /// </summary>
        public static string InvoiceTitle {
            get {
                return ResourceManager.GetString("InvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руссий язык используется для интерфейса.
        /// </summary>
        public static string LanguageWasSetSuccessfully {
            get {
                return ResourceManager.GetString("LanguageWasSetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример запроса для создания музыки:
        ///&quot;Напиши расслабленный лоу-фай бит с джазовыми аккордами на пианино, винтажным виниловым шумом, мягким кик-барабаном и щелчками на 2 и 4. Темп: 85 BPM. Добавь немного джазовой бас-линии и случайные звуки (скрип двери, голоса в фоне).&quot;
        ///
        ///Бот отправит звуковой файл длительностью до 30 секунд. Стоимость генерации 10 stars.
        /// </summary>
        public static string MusicResponse {
            get {
                return ResourceManager.GetString("MusicResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но сейчас доступна обработка только текстовых сообщений. В разработке находятся голосовые сообщения и генерация картинок текстом.
        /// </summary>
        public static string OnlyMessagesAvailable {
            get {
                return ResourceManager.GetString("OnlyMessagesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Ведутся технические работы. Благодарим за понимание..
        /// </summary>
        public static string OnMaintenance {
            get {
                return ResourceManager.GetString("OnMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык интерфейса(влияет только на перевод кнопок, общаться можно на люом языке).
        /// </summary>
        public static string PleaseSetLanguage {
            get {
                return ResourceManager.GetString("PleaseSetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌛️ Подождите, подготавливаю ответ....
        /// </summary>
        public static string PleaseWaitMsg {
            get {
                return ResourceManager.GetString("PleaseWaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌛️ Генерация видео занимает в срднем от 5 до 10 минут. Подождите, подготавливаю ответ....
        /// </summary>
        public static string PleaseWaitVideoMsg {
            get {
                return ResourceManager.GetString("PleaseWaitVideoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Профиль: {0} {1}
        ///
        ///
        ///💵 Баланс: {2} Stars 💵
        ///Количество бесплатных запросов:
        /// -- запросов к ChatGpt: {3}
        /// -- генераций изображений: {4}
        /// -- распознаваний текста: {5}
        ///.
        /// </summary>
        public static string ProfileResponse {
            get {
                return ResourceManager.GetString("ProfileResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я отутствовал какое-то время, но сейчас снова в строю..
        /// </summary>
        public static string Recovered {
            get {
                return ResourceManager.GetString("Recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сообщение ниже. Будем рады любой обратной связи..
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для распознавания текста на изображении сначала выберите команду из меню.
        /// </summary>
        public static string SendImageTextRecognitionCommandFirst {
            get {
                return ResourceManager.GetString("SendImageTextRecognitionCommandFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте изображение для распознавания текста или нажмите /cancel для отмены.
        /// </summary>
        public static string SendTextRecognitionImage {
            get {
                return ResourceManager.GetString("SendTextRecognitionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бот отвечает на вопросы и создает изображения🤖👋 (@my_super_ultra_smart_bot).
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служебный бот для разработки, добавляйте @GPTipsBot.
        /// </summary>
        public static string ShortDevDescription {
            get {
                return ResourceManager.GetString("ShortDevDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Закончился лимит бесплатных запросов на сегодня.
        ///Пополните баланс или дождитесь обновления бесплатных лимитов
        ///
        ///1⭐ = 10 запросам к ChatGpt или 2 генерации изображения.
        /// </summary>
        public static string SimpleNoFreeRequests {
            get {
                return ResourceManager.GetString("SimpleNoFreeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так, попробуйте ещё раз.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис генерации изображений находится в тестовом режиме. Попробуйте заново, начиная с команды /image, либо дождитесь исправления ошибок. Мы работаем над улучшением сервиса, благодарим за понимание 🙏.
        /// </summary>
        public static string SomethingWentWrongWithImageService {
            get {
                return ResourceManager.GetString("SomethingWentWrongWithImageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст песни. Стоимость генерации 20 stars.
        /// </summary>
        public static string SongResponse {
            get {
                return ResourceManager.GetString("SongResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать бесплатное прокси: {0}.
        /// </summary>
        public static string SwitchProxy {
            get {
                return ResourceManager.GetString("SwitchProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Закончился лимит бесплатных запросов на сегодня.
        ///Пополните баланс или дождитесь обновления бесплатных запросов через {0:%d} д {0:%h} ч {0:%m} мин
        ///
        ///1⭐ = 10 запросам к ChatGPT или 2 генерации изображения.
        /// </summary>
        public static string TimeNoFreeRequests {
            get {
                return ResourceManager.GetString("TimeNoFreeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество токенов в вашем сообщении {1} превышает лимит в {0} токенов. Сократите своё сообщение. Считайте, что в одном слове содержится примерно 1 токен.
        /// </summary>
        public static string TokensLimitExceeded {
            get {
                return ResourceManager.GetString("TokensLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️Слишком много запросов в минуту, попробуйте позже.
        /// </summary>
        public static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Отправьте фото с описанием (заголовком). Бот добавит анимацию к объектам на фото: машина едет, люди улыбаются и тд
        ///Результат: gif файл длительностью до 5 секунд, время генерации от 5 до 10 минут
        ///Это бета-версия функционала, может работать не стабильно
        ///Стоимость генерации {0} stars
        ///    .
        /// </summary>
        public static string VideoInstructions {
            get {
                return ResourceManager.GetString("VideoInstructions", resourceCulture);
            }
        }
    }
}
