//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTipsBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPTipsBot.Resources.BotUI", typeof(BotUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Оживить фото.
        /// </summary>
        internal static string AnimateButton {
            get {
                return ResourceManager.GetString("AnimateButton", resourceCulture);
            }
        }
        
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        internal static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }

        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }

        internal static string ModelButton {
            get {
                return ResourceManager.GetString("ModelButton", resourceCulture);
            }
        }

        internal static string GptImage {
            get {
                return ResourceManager.GetString("GptImage", resourceCulture);
            }
        }

        internal static string GptImageButton {
            get {
                return ResourceManager.GetString("GptImageButton", resourceCulture);
            }
        }

        internal static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }

        internal static string EditImageButton {
            get {
                return ResourceManager.GetString("EditImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс.
        /// </summary>
        internal static string DepositButton {
            get {
                return ResourceManager.GetString("DepositButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌟 Поддержите наш проект! 💪
        ///
        ///💖 Каждый донат помогает развивать и улучшать сервис. 🤝 Мы ценим вашу поддержку и работаем над тем, чтобы сделать наш продукт еще лучше. 🚀💡.
        /// </summary>
        internal static string DonateButton {
            get {
                return ResourceManager.GetString("DonateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция по применению.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❔ Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать изображение по текстовому описанию.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖼 Создать изображение.
        /// </summary>
        internal static string ImageButton {
            get {
                return ResourceManager.GetString("ImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст на изображении.
        /// </summary>
        internal static string ImageTextRecognize {
            get {
                return ResourceManager.GetString("ImageTextRecognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распознать текст на изображении.
        /// </summary>
        internal static string ImageTextRecognizeButton {
            get {
                return ResourceManager.GetString("ImageTextRecognizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string LangButton {
            get {
                return ResourceManager.GetString("LangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Личный кабинет.
        /// </summary>
        internal static string ProfileButton {
            get {
                return ResourceManager.GetString("ProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать новый диалог с ChatGPT (сбросить контекст).
        /// </summary>
        internal static string ResetContext {
            get {
                return ResourceManager.GetString("ResetContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💬 Новый диалог с ChatGPT (сбросить контекст).
        /// </summary>
        internal static string ResetContextButton {
            get {
                return ResourceManager.GetString("ResetContextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string RussianButton {
            get {
                return ResourceManager.GetString("RussianButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string SetEngLang {
            get {
                return ResourceManager.GetString("SetEngLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить язык интерфейса бота.
        /// </summary>
        internal static string SetLang {
            get {
                return ResourceManager.GetString("SetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string SetRuLang {
            get {
                return ResourceManager.GetString("SetRuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать пользоваться ботом.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отменить запрос.
        /// </summary>
        internal static string StopRequestButton {
            get {
                return ResourceManager.GetString("StopRequestButton", resourceCulture);
            }
        }
    }
}
