//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTipsBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPTipsBot.Resources.BotUI", typeof(BotUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гадание по книгам.
        /// </summary>
        internal static string BookDivinationButton {
            get {
                return ResourceManager.GetString("BookDivinationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмодзи ребус.
        /// </summary>
        internal static string EmojiTranslationButton {
            get {
                return ResourceManager.GetString("EmojiTranslationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить отзыв.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить отзыв.
        /// </summary>
        internal static string FeedbackButton {
            get {
                return ResourceManager.GetString("FeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игры.
        /// </summary>
        internal static string GamesButton {
            get {
                return ResourceManager.GetString("GamesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отгадай кто.
        /// </summary>
        internal static string GuessWhoButton {
            get {
                return ResourceManager.GetString("GuessWhoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция по применению.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❔ Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать изображение по текстовому описанию.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖼 Создать изображение.
        /// </summary>
        internal static string ImageButton {
            get {
                return ResourceManager.GetString("ImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string LangButton {
            get {
                return ResourceManager.GetString("LangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать новый диалог с ChatGPT (сбросить контекст).
        /// </summary>
        internal static string ResetContext {
            get {
                return ResourceManager.GetString("ResetContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💬 Новый диалог с ChatGPT (сбросить контекст).
        /// </summary>
        internal static string ResetContextButton {
            get {
                return ResourceManager.GetString("ResetContextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string RussianButton {
            get {
                return ResourceManager.GetString("RussianButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string SetEngLang {
            get {
                return ResourceManager.GetString("SetEngLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить язык интерфейса бота.
        /// </summary>
        internal static string SetLang {
            get {
                return ResourceManager.GetString("SetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string SetRuLang {
            get {
                return ResourceManager.GetString("SetRuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать пользоваться ботом.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отменить запрос.
        /// </summary>
        internal static string StopRequestButton {
            get {
                return ResourceManager.GetString("StopRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крестики нолики.
        /// </summary>
        internal static string TickTackToeButton {
            get {
                return ResourceManager.GetString("TickTackToeButton", resourceCulture);
            }
        }
    }
}
