//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTipsBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChatGptGamesPrompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatGptGamesPrompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPTipsBot.Resources.ChatGptGamesPrompts", typeof(ChatGptGamesPrompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давай сыграем в игру &quot;Book divination&quot; - гадание по книге. 1. Предложи пользователю для гадания популярные книги 2. Пользователь должен написать на что он гадает. Какой вопрос его беспокоит 3. Случайным образом выбери строчку или абзац из книги и интерпретируй её для пользователя. Перед началом игры расскажи правила..
        /// </summary>
        internal static string BookDivination {
            get {
                return ResourceManager.GetString("BookDivination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давай сыграем в Emoji Translation. 1. Отправь пользователю название известного фильма, мультфильма или книги в виде последовательности эмодзи. 2. Пользователь должен угадать название. Перед началом игры расскажи правила..
        /// </summary>
        internal static string EmojiTranslation {
            get {
                return ResourceManager.GetString("EmojiTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я загадываю известного персонажа. Задавай мне вопросы, предполагающие ответы да или нет. На основании моих ответов, ты должен угадать, какого персонажа я загадал(а). Начни задавать вопросы. Перед началом расскажи правила..
        /// </summary>
        internal static string GuessWho {
            get {
                return ResourceManager.GetString("GuessWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давай сыграем в в крестики нолики. Предложи мне выбрать за какой символ я буду играть, за крестик или нолик. Отслеживай мои ходы и обновляй поле, каждый раз. Когда будешь обновлять поле каждый раз проверяй результат, если есть победитель или ничья напиши &quot;Кабалунгма&quot;.
        /// </summary>
        internal static string TickTacToe {
            get {
                return ResourceManager.GetString("TickTacToe", resourceCulture);
            }
        }
    }
}
